// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Entry struct {
	ID      int32     `json:"id"`
	Owner   string    `json:"owner"`
	Name    string    `json:"name"`
	DueDate time.Time `json:"due_date"`
	// must be positive
	Amount   int64          `json:"amount"`
	Category sql.NullString `json:"category"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	TotalExpenses     int64     `json:"total_expenses"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
